export { default as HomePage } from './Home'
export { default as CreatePage } from './Create'
export { default as InfoPage } from './Info/Info'
export {default as UpdatePage} from './Update/UpdatePage'
export { default as LoginPage} from './Login/Login'